# Generated by Django 2.2.7 on 2023-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview_slot",
            name="calendar_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="interview_slot",
            name="join_url",
            field=models.TextField(null=True),
        ),
    ]
