# Generated by Django 2.2.7 on 2023-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_event", "0002_auto_20230813_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview_slot",
            name="calendar_id",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
