# Generated by Django 2.2.7 on 2024-01-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0014_attendees_role_summary"),
        ("schedule_event", "0004_interview_slot_jd_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview_slot",
            name="interview_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarapp.CalEvents",
            ),
        ),
    ]
