# Generated by Django 2.2.7 on 2024-02-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0015_auto_20240202_0603"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule_event", "0005_interview_slot_interview_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="website_userinfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=1000, null=True)),
                ("name", models.CharField(max_length=1000, null=True)),
                ("email", models.CharField(max_length=1000, null=True)),
                ("description", models.TextField(null=True)),
                ("contact", models.TextField(max_length=1000, null=True)),
                ("destination", models.TextField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule_event.Event_scheduler",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="website_useraccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="website_event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, null=True)),
                ("startevent", models.CharField(max_length=100, null=True)),
                ("endevent", models.CharField(max_length=100, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=255)),
                ("calendar_id", models.TextField(null=True)),
                ("join_url", models.TextField(null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule_event.website_userinfo",
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule_event.Event_scheduler",
                    ),
                ),
                (
                    "interview_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarapp.CalEvents",
                    ),
                ),
            ],
        ),
    ]
