# Generated by Django 2.2.7 on 2023-07-31 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobspipeline", "__first__"),
        ("main", "__first__"),
        ("application", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="applicant_add_on_plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_count", models.IntegerField(null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="employer_pool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, null=True)),
                ("last_name", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("contact", models.CharField(max_length=200, null=True)),
                ("login_shared", models.BooleanField(null=True)),
                ("linkedin_url", models.CharField(max_length=200, null=True)),
                ("work_exp", models.CharField(max_length=200, null=True)),
                ("relocate", models.BooleanField(null=True)),
                ("qualification", models.CharField(max_length=200, null=True)),
                ("exp_salary", models.CharField(max_length=200, null=True)),
                ("job_title", models.CharField(max_length=200, null=True)),
                ("candi_ref_id", models.CharField(max_length=200, null=True)),
                ("skills", models.TextField(max_length=10000, null=True)),
                ("location", models.CharField(max_length=2000, null=True)),
                ("updated_on", models.DateField(auto_now_add=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="JD_form",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_posted_on", models.DateTimeField(auto_now_add=True)),
                ("job_reposted_on", models.DateTimeField(null=True)),
                ("job_title", models.CharField(max_length=60)),
                ("job_id", models.CharField(max_length=15)),
                ("visa_sponsor", models.BooleanField(default=True, max_length=10)),
                ("company_name", models.CharField(max_length=60)),
                ("company_website", models.URLField(max_length=100)),
                ("no_of_vacancies", models.IntegerField(null=True)),
                (
                    "company_logo",
                    models.FileField(
                        default="default_logo.png", upload_to="company_logo/"
                    ),
                ),
                ("org_info", models.TextField(max_length=10000, null=True)),
                ("min_exp", models.FloatField()),
                ("max_exp", models.IntegerField(null=True)),
                ("is_ds_role", models.BooleanField(null=True)),
                ("is_eeo_comp", models.BooleanField(null=True)),
                ("work_remote", models.BooleanField(default=False, null=True)),
                ("role_res", models.TextField(max_length=10000)),
                ("job_description", models.TextField(max_length=10000, null=True)),
                (
                    "richtext_job_description",
                    models.TextField(max_length=1000, null=True),
                ),
                ("tech_req", models.TextField(max_length=1000)),
                ("non_tech_req", models.TextField(max_length=1000)),
                ("updated_by", models.CharField(max_length=100, null=True)),
                ("add_info", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "salary_min",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9999999)],
                    ),
                ),
                (
                    "salary_max",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9999999)],
                    ),
                ),
                (
                    "show_sal_to_candidate",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "industry_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.tmeta_industry_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="recuriter_job_posting_plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_invites", models.IntegerField(null=True)),
                ("available_applicants", models.IntegerField(null=True)),
                ("featured_days", models.IntegerField(null=True)),
                ("available_days", models.IntegerField(null=True)),
                ("has_external_promotion", models.BooleanField(default=False)),
                ("available_view_contacts", models.IntegerField(null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField(null=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subscriptions",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("subscription_start_ts", models.DateTimeField(auto_now_add=True)),
                ("subscription_valid_till", models.DateTimeField(null=True)),
                ("subscription_end_ts", models.DateTimeField(null=True)),
                ("subscription_changed_date", models.DateTimeField(null=True)),
                ("subscription_changed_to", models.IntegerField(null=True)),
                ("no_of_users", models.IntegerField(null=True)),
                ("subscription_remains_days", models.IntegerField(null=True)),
                ("auto_renewal", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("has_client_changed_subscription", models.BooleanField(default=False)),
                ("updated_by", models.CharField(max_length=255)),
                ("grace_period_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_candidate_source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=1)),
                ("description", models.CharField(max_length=1000, null=True)),
                ("label_name", models.CharField(max_length=100, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_career_page_plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("job_posting", models.BooleanField(default=True)),
                ("questionnaire", models.BooleanField(default=True)),
                ("career_page", models.BooleanField(default=True)),
                ("has_external_posting", models.BooleanField(default=True)),
                ("zita_match", models.BooleanField(default=True)),
                ("applicant_access", models.BooleanField(default=True)),
                ("job_featuring", models.BooleanField()),
                ("has_external_promotion", models.BooleanField()),
                ("tailored_email", models.BooleanField(default=False)),
                ("label_name", models.CharField(max_length=100)),
                ("validity_days", models.IntegerField(default=0)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_currency_type",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("label_name", models.CharField(max_length=100)),
                ("sequence", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_email_preference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inactivated_date", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_external_jobposting_detail",
            fields=[
                ("ext_jp_site_id", models.AutoField(primary_key=True, serialize=False)),
                ("ext_jp_site_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicant_intake_format",
                    models.CharField(max_length=255, null=True),
                ),
                ("added_date", models.DateTimeField(null=True)),
                ("inactivated_date", models.DateTimeField(null=True)),
                ("jobposting_format", models.CharField(max_length=255)),
                ("updated_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_features",
            fields=[
                ("feature_id", models.AutoField(primary_key=True, serialize=False)),
                ("feature_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inactivated_date", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_field_types",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=1)),
                ("description", models.CharField(max_length=1000)),
                ("label_name", models.CharField(max_length=100, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_jd_candidate_status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=1)),
                ("description", models.CharField(max_length=1000)),
                ("label_name", models.CharField(max_length=100, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_jd_status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=1)),
                ("description", models.CharField(max_length=1000, null=True)),
                ("label_name", models.CharField(max_length=100, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_jd_templates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_description", models.TextField()),
                ("job_title", models.CharField(max_length=1000, null=True)),
                ("qualification", models.CharField(max_length=1000, null=True)),
                ("experience", models.CharField(max_length=1000, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("is_ds_role", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_job_posting_add_on",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("applicant_count", models.IntegerField(null=True)),
                ("label_name", models.CharField(max_length=100)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_job_posting_plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("invites_count", models.IntegerField(null=True)),
                ("view_contact_count", models.IntegerField(null=True)),
                ("validity_days", models.IntegerField(null=True)),
                ("featured_days", models.IntegerField(null=True)),
                ("applicant_count", models.IntegerField(null=True)),
                ("has_external_promotion", models.BooleanField(default=False)),
                ("label_name", models.CharField(max_length=100)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_message_templates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("templates", models.TextField()),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_plan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=255)),
                ("subscription_value_days", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                ("currency", models.CharField(max_length=255)),
                ("stripe_id", models.CharField(max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inactived_date", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="tmeta_skills_category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=1)),
                ("description", models.CharField(max_length=1000)),
                ("label_name", models.CharField(max_length=100, null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="zita_talent_sourcing_channels",
            fields=[
                ("ts_channel_id", models.AutoField(primary_key=True, serialize=False)),
                ("ts_channel_name", models.CharField(max_length=255)),
                ("ts_cost_per_talent", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Zita_match_count",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="zita_match_candidates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=500, null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_jd_candidate_status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subscriptions_feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.CharField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.subscriptions",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="plan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.tmeta_plan"
            ),
        ),
        migrations.CreateModel(
            name="recuriter_payment_history",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("price", models.IntegerField(null=True)),
                ("invoice_id", models.CharField(max_length=50, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "add_on_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.applicant_add_on_plan",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "job_posting_plan_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.recuriter_job_posting_plan",
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_job_posting_plan",
                    ),
                ),
                (
                    "recruiter_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recuriter_job_posting_plan",
            name="plan_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.tmeta_job_posting_plan",
            ),
        ),
        migrations.AddField(
            model_name="recuriter_job_posting_plan",
            name="recruiter_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="plan_features",
            fields=[
                (
                    "plan_feature_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("feature_value", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_features",
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pipeline_view",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=500, null=True)),
                ("stage_order", models.CharField(max_length=100, null=True)),
                ("stage_name", models.CharField(max_length=100, null=True)),
                ("stage_color", models.CharField(max_length=100, null=True)),
                ("stage_length", models.IntegerField(default=0)),
                ("is_disabled", models.BooleanField(default=False)),
                (
                    "emp_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "workflow_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobspipeline.Employee_workflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Missing_Skills_Table",
            fields=[
                ("miss_skill_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "missingskill_mand",
                    models.TextField(max_length=5000, verbose_name="Mandatory Skills*"),
                ),
                (
                    "missingskill_pl",
                    models.TextField(blank=True, max_length=5000, verbose_name=""),
                ),
                (
                    "missingskill_db",
                    models.TextField(blank=True, max_length=5000, verbose_name=""),
                ),
                (
                    "missingskill_tl",
                    models.TextField(blank=True, max_length=5000, verbose_name=""),
                ),
                (
                    "missingskill_pf",
                    models.TextField(blank=True, max_length=5000, verbose_name=""),
                ),
                (
                    "missingskill_ot",
                    models.TextField(blank=True, max_length=5000, verbose_name=""),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message_non_applicants",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_read", models.BooleanField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mention_Candidate_notes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_names", models.CharField(max_length=1000, null=True)),
                ("updated_by", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matched_candidates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_match", models.FloatField(max_length=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="jobs_eeo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Decline to Self identify", "Decline to Self identify"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "hispanic_latino",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Decline to Self identify", "Decline to Self identify"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "veteran_status",
                    models.CharField(
                        choices=[
                            (
                                "I am not a protected Veteran",
                                "I am not a protected Veteran",
                            ),
                            (
                                "I identify as one or more of the classifications of a protected veteran",
                                "I identify as one or more of the classifications of a protected veteran",
                            ),
                            ("I don`t wish to answer", "I don`t wish to answer"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "disability_status",
                    models.CharField(
                        choices=[
                            (
                                "Yes, I have a disability or have a history/record of having a disability",
                                "Yes, I have a disability or have a history/record of having a disability",
                            ),
                            (
                                "No, I don`t have a disability or a history/record of having a disability",
                                "No, I don`t have a disability or a history/record of having a disability",
                            ),
                            ("I don`t wish to answer", "I don`t wish to answer"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                ("identify_race", models.CharField(max_length=500, null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.Personal_Info",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="job_view_count",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(null=True)),
                ("source", models.CharField(max_length=500, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JDUploads",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jd_path", models.CharField(blank=True, max_length=500)),
                ("photo_path", models.CharField(blank=True, default=0, max_length=500)),
                (
                    "parsed_file",
                    models.CharField(blank=True, default=0, max_length=1000),
                ),
                (
                    "application_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JDfiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jd_file", models.FileField(default=0, upload_to="uploaded_jds/")),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jdfiles_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JD_skills_experience",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.TextField(max_length=100)),
                ("experience", models.CharField(default=0, max_length=20)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_skills_category",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JD_qualification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification", models.CharField(max_length=100)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JD_profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_intelligence",
                    models.CharField(blank=True, default=0, max_length=200),
                ),
                (
                    "data_analysis",
                    models.CharField(blank=True, default=0, max_length=200),
                ),
                (
                    "data_engineering",
                    models.CharField(blank=True, default=0, max_length=200),
                ),
                ("devops", models.CharField(blank=True, default=0, max_length=200)),
                (
                    "machine_learning",
                    models.CharField(blank=True, default=0, max_length=200),
                ),
                ("others", models.CharField(blank=True, default=0, max_length=200)),
                ("dst_or_not", models.CharField(blank=True, default=2, max_length=20)),
                ("role_acceptence", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
                (
                    "recommended_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tmeta_ds_main_roles",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="jd_parsed_details",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parsed_text", models.TextField(max_length=50000, null=True)),
                ("resume_file_path", models.TextField(max_length=2000, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jd_parsed_details_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JD_locations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(max_length=50, null=True)),
                ("lng", models.FloatField(max_length=50, null=True)),
                ("location", models.CharField(max_length=200, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="application.City",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="application.Country",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="application.State",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jd_form",
            name="jd_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.tmeta_jd_status",
            ),
        ),
        migrations.AddField(
            model_name="jd_form",
            name="job_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tmeta_ds_main_roles",
            ),
        ),
        migrations.AddField(
            model_name="jd_form",
            name="job_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="application.tmeta_job_type",
            ),
        ),
        migrations.AddField(
            model_name="jd_form",
            name="salary_curr_type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.tmeta_currency_type",
            ),
        ),
        migrations.AddField(
            model_name="jd_form",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="jd_candidate_analytics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_location",
                    models.CharField(default="", max_length=500, null=True),
                ),
                ("interested", models.BooleanField(default=0)),
                ("contacted", models.BooleanField(default=0)),
                ("rejected", models.BooleanField(default=0)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.Personal_Info",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "recruiter_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shortlisted_role_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tmeta_ds_main_roles",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_jd_candidate_status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="interview_scorecard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField(default=0)),
                ("comments", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback_form",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, null=True)),
                ("email", models.CharField(max_length=500, null=True)),
                ("rating", models.IntegerField(default=0)),
                ("comments", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="favourites",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="external_jobpostings_by_client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posted_on", models.DateTimeField(auto_now_add=True)),
                ("posted_by", models.CharField(max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("jobposting_url", models.CharField(max_length=255, null=True)),
                ("job_posting_ref_id", models.CharField(max_length=255, null=True)),
                ("job_inactivated_on", models.DateTimeField(null=True)),
                ("job_inactivated_by", models.CharField(max_length=255, null=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ext_jp_site_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_external_jobposting_detail",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employer_pool",
            name="can_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.tmeta_candidate_source",
            ),
        ),
        migrations.AddField(
            model_name="employer_pool",
            name="candidate_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.Personal_Info",
            ),
        ),
        migrations.AddField(
            model_name="employer_pool",
            name="client_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employer_pool",
            name="favourite",
            field=models.ManyToManyField(
                blank=True,
                related_name="favourite",
                through="jobs.favourites",
                to="jobs.JD_form",
            ),
        ),
        migrations.AddField(
            model_name="employer_pool",
            name="jd_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.JD_form",
            ),
        ),
        migrations.AddField(
            model_name="employer_pool",
            name="job_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.tmeta_job_type",
            ),
        ),
        migrations.AddField(
            model_name="employer_pool",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="email_preference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=255)),
                (
                    "stage_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_email_preference",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="discounts",
            fields=[
                ("discount_id", models.AutoField(primary_key=True, serialize=False)),
                ("discount_name", models.CharField(max_length=255)),
                ("discount_code", models.CharField(max_length=255)),
                ("discount_type", models.CharField(max_length=255)),
                ("discount_value", models.IntegerField(default=0)),
                ("discount_currency", models.CharField(max_length=255)),
                ("discount_start_date", models.DateTimeField(null=True)),
                ("discount_end_date", models.DateTimeField(null=True)),
                ("usage_per_client", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="discount_codes_claimed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discount_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.discounts"
                    ),
                ),
                (
                    "subscription_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.subscriptions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="daily_visualise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("y", models.CharField(blank=True, default=0, max_length=2000)),
                ("v_type", models.CharField(blank=True, default=0, max_length=2000)),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="company_details",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_website", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=200)),
                ("no_of_emp", models.IntegerField(null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("zipcode", models.CharField(max_length=500, null=True)),
                ("updated_by", models.CharField(max_length=100, null=True)),
                ("logo", models.FileField(null=True, upload_to="company_logo")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="application.City",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="application.Country",
                    ),
                ),
                (
                    "industry_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.tmeta_industry_type",
                    ),
                ),
                (
                    "recruiter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="application.State",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="client_features_balance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_count", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_features",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="client_addons_purchase_history",
            fields=[
                (
                    "client_addon_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("purchased_count", models.IntegerField(null=True)),
                ("purchased_date", models.DateField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_features",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="career_page_setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_font", models.CharField(max_length=200, null=True)),
                ("header_font_size", models.IntegerField(null=True)),
                ("header_color", models.CharField(max_length=200, null=True)),
                ("menu_1", models.CharField(max_length=200, null=True)),
                ("menu_1_url", models.CharField(max_length=200, null=True)),
                ("menu_2", models.CharField(max_length=200, null=True)),
                ("menu_2_url", models.CharField(max_length=200, null=True)),
                ("menu_3", models.CharField(max_length=200, null=True)),
                ("menu_3_url", models.CharField(max_length=200, null=True)),
                ("page_font_size", models.IntegerField(null=True)),
                (
                    "banner_img",
                    models.FileField(default="slider1.jpg", upload_to="banner_img"),
                ),
                ("banner_header_text", models.CharField(max_length=200, null=True)),
                ("banner_text", models.CharField(max_length=2000, null=True)),
                ("banner_font_size", models.IntegerField(null=True)),
                ("banner_heading_size", models.IntegerField(null=True)),
                ("about_us", models.CharField(max_length=500)),
                ("button_color", models.CharField(max_length=200, null=True)),
                ("footer_color", models.CharField(max_length=200, null=True)),
                ("updated_by", models.CharField(max_length=100, null=True)),
                ("career_page_url", models.CharField(max_length=200, null=True)),
                (
                    "recruiter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="candidate_resume",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="candidate_resume/", verbose_name="Document"
                    ),
                ),
                ("is_parsed", models.BooleanField(default=False)),
                ("updated_by", models.CharField(max_length=100, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="candidate_parsed_details",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parsed_text", models.TextField(blank=True, max_length=50000)),
                (
                    "resume_file_path",
                    models.FileField(default=0, upload_to="candidate_resume/"),
                ),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate_notes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(max_length=2000, null=True)),
                ("updated_by", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candi_invite_to_apply",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_interested", models.BooleanField(null=True)),
                ("updated_by", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("responded_date", models.DateTimeField(null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="application_form",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=2000)),
                ("last_name", models.CharField(blank=True, max_length=2000)),
                ("email", models.CharField(blank=True, max_length=2000)),
                ("contact", models.CharField(blank=True, max_length=2000)),
                ("location", models.CharField(blank=True, max_length=2000)),
                ("linkedin_url", models.URLField(blank=True, max_length=2000)),
                ("cv_file", models.FileField(default=0, upload_to="applicant_Resume/")),
                (
                    "candidate_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.Personal_Info",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="applicants_status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=500, null=True)),
                ("source", models.CharField(max_length=500, null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "stage_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.pipeline_view",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_jd_candidate_status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="applicants_screening_status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=500, null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "stage_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.pipeline_view",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="applicant_questionnaire_template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1000, null=True)),
                ("is_required", models.BooleanField(null=True)),
                ("description", models.TextField(max_length=10000, null=True)),
                ("option1", models.CharField(max_length=1000, null=True)),
                ("option2", models.CharField(max_length=1000, null=True)),
                ("option3", models.CharField(max_length=1000, null=True)),
                ("option4", models.CharField(max_length=1000, null=True)),
                (
                    "field_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_field_types",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="applicant_questionnaire",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1000, null=True)),
                ("description", models.TextField(max_length=10000, null=True)),
                ("is_required", models.BooleanField(null=True)),
                ("option1", models.CharField(max_length=1000, null=True)),
                ("option2", models.CharField(max_length=1000, null=True)),
                ("option3", models.CharField(max_length=1000, null=True)),
                ("option4", models.CharField(max_length=1000, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "field_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_field_types",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="applicant_cover_letter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField(blank=True, max_length=20000)),
                ("source", models.CharField(blank=True, max_length=1000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.Personal_Info",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="applicant_answers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(blank=True, max_length=10000)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.Personal_Info",
                    ),
                ),
                (
                    "qus_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.applicant_questionnaire",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="applicant_add_on_plan",
            name="add_on_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.tmeta_job_posting_add_on",
            ),
        ),
        migrations.AddField(
            model_name="applicant_add_on_plan",
            name="jd_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.JD_form",
            ),
        ),
        migrations.AddField(
            model_name="applicant_add_on_plan",
            name="recruiter_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
