# Generated by Django 2.2.7 on 2023-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_career_page_setting_font_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmeta_message_templates",
            name="templates_text",
            field=models.TextField(null=True),
        ),
    ]
