# Generated by Django 2.2.7 on 2023-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_tmeta_message_templates_templates_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmeta_jd_templates",
            name="skills",
            field=models.TextField(null=True),
        ),
    ]
