# Generated by Django 2.2.7 on 2023-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_tmeta_jd_templates_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="jd_form",
            name="work_space_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
