# Generated by Django 2.2.7 on 2023-09-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jd_form_work_space_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matched_percentage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("percentage", models.FloatField(max_length=25)),
                ("description", models.TextField(null=True)),
                ("overall_percentage", models.FloatField(max_length=25)),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.employer_pool",
                    ),
                ),
                (
                    "jd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.JD_form"
                    ),
                ),
            ],
        ),
    ]
