# Generated by Django 2.2.7 on 2023-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jd_form_work_space_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="whatjob_activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jd_id", models.IntegerField(null=True)),
                ("whatjob", models.BooleanField(default=False)),
            ],
        ),
    ]
