# Generated by Django 2.2.7 on 2023-10-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_whatjob_activity"),
        ("jobs", "0009_matched_percentage"),
    ]

    operations = []
