# Generated by Django 2.2.7 on 2023-10-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_jd_tech_matching"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jd_tech_matching",
            name="jd_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.JD_form",
            ),
        ),
    ]
