# Generated by Django 2.2.7 on 2023-11-01 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0013_auto_20231026_0720"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmeta_jd_templates",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tmeta_message_templates",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tmeta_message_templates",
            name="subject",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tmeta_message_templates",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
