# Generated by Django 2.2.7 on 2023-11-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_auto_20231101_0510"),
        ("jobs", "0014_tmeta_weightage_criteria_weightage_matching"),
    ]

    operations = []
