# Generated by Django 2.2.7 on 2023-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_bulk_matching"),
    ]

    operations = [
        migrations.AddField(
            model_name="addons_plan_features",
            name="stripe_id",
            field=models.TextField(null=True),
        ),
    ]
