# Generated by Django 2.2.7 on 2023-12-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0022_auto_20231201_0618"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_features_balance",
            name="add_ons",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.tmeta_addons",
            ),
        ),
        migrations.AddField(
            model_name="tmeta_addons",
            name="display_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tmeta_addons",
            name="feature_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.tmeta_features",
            ),
        ),
        migrations.AddField(
            model_name="tmeta_features",
            name="display_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
