# Generated by Django 2.2.7 on 2023-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0023_auto_20231201_1057"),
    ]

    operations = [
        migrations.AddField(
            model_name="addons_plan_features",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
