# Generated by Django 2.2.7 on 2023-12-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0012_calevents_addon"),
        ("jobs", "0029_client_features_balance_addons_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="score_categories",
            name="interview_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarapp.CalEvents",
            ),
        ),
    ]
