# Generated by Django 2.2.7 on 2023-12-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0012_calevents_addon"),
        ("jobs", "0030_score_categories_interview_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview_scorecard",
            name="interview_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarapp.CalEvents",
            ),
        ),
    ]
