# Generated by Django 2.2.7 on 2023-12-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0031_interview_scorecard_interview_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate_parsed_details",
            name="resume_description",
            field=models.TextField(null=True),
        ),
    ]
