# Generated by Django 2.2.7 on 2024-02-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0037_pipeline_status_stages_customization_tmeta_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="stages_customization",
            name="is_compelted",
            field=models.BooleanField(default=False),
        ),
    ]
