# Generated by Django 2.2.7 on 2024-03-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0040_email_automation_template_tmeta_automation_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email_automation_template",
            name="subject",
        ),
        migrations.AddField(
            model_name="tmeta_automation_template",
            name="subject",
            field=models.TextField(null=True),
        ),
    ]
