# Generated by Django 2.2.7 on 2024-03-18 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0041_auto_20240316_1658"),
    ]

    operations = [
        migrations.CreateModel(
            name="tour_data",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_first_login", models.BooleanField(null=True)),
                ("skip_id", models.IntegerField(null=True)),
                ("feedback_rating", models.IntegerField(null=True)),
                ("feedback_notes", models.TextField(null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
