# Generated by Django 2.2.7 on 2024-03-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0042_template_stage"),
        ("jobs", "0042_tour_data"),
    ]

    operations = []
