# Generated by Django 2.2.7 on 2024-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0044_tour_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline_view",
            name="email_toggle",
            field=models.BooleanField(default=False),
        ),
    ]
