# Generated by Django 2.2.7 on 2024-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0045_pipeline_view_email_toggle"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmeta_automation_template",
            name="stage",
            field=models.TextField(null=True),
        ),
    ]
