# Generated by Django 2.2.7 on 2024-03-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0046_tmeta_automation_template_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmeta_automation_template",
            name="jd_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.JD_form",
            ),
        ),
    ]
