# Generated by Django 2.2.7 on 2024-03-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0047_tmeta_automation_template_jd_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmeta_automation_template",
            name="stages",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.pipeline_view",
            ),
        ),
    ]
