# Generated by Django 2.2.7 on 2024-03-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0048_tmeta_automation_template_stages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template_stage",
            name="templates",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.tmeta_message_templates",
            ),
        ),
    ]
