# Generated by Django 2.2.7 on 2024-03-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0050_template_stage_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmeta_message_templates",
            name="jd_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.JD_form",
            ),
        ),
    ]
