# Generated by Django 2.2.7 on 2024-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0050_template_stage_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour_data",
            name="is_steps",
            field=models.BooleanField(null=True),
        ),
    ]
