# Generated by Django 2.2.7 on 2024-04-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0053_linkedin_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedin_data",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="linkedin_data",
            name="is_unlocked",
            field=models.BooleanField(default=False),
        ),
    ]
