# Generated by Django 2.2.7 on 2024-04-04 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0055_unlocked_candidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedin_data",
            name="candidate_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.employer_pool",
            ),
        ),
    ]
