# Generated by Django 2.2.7 on 2024-04-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0056_linkedin_data_candidate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer_pool",
            name="job_title",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
