# Generated by Django 2.2.7 on 2024-04-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0057_auto_20240404_0547"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedin_data",
            name="resume_file_path",
            field=models.TextField(null=True),
        ),
    ]
