# Generated by Django 2.2.7 on 2024-04-11 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0058_linkedin_data_resume_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedin_data",
            name="linkedin_source_data",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="unlocked_candidate",
            name="candidate_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.employer_pool",
            ),
        ),
        migrations.AddField(
            model_name="unlocked_candidate",
            name="email",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="unlocked_candidate",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unlocked_candidate",
            name="resume_file_path",
            field=models.TextField(null=True),
        ),
    ]
