# Generated by Django 2.2.7 on 2024-04-21 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0059_auto_20240411_0745"),
    ]

    operations = [
        migrations.CreateModel(
            name="tmeta_coresignal_data",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedin_id", models.IntegerField(null=True)),
                ("sourcing_data", models.TextField(null=True)),
                ("linkedin_source_data", models.TextField(null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=500, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
