# Generated by Django 2.2.7 on 2024-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0060_auto_20240416_1207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tmeta_message_templates",
            name="stage",
            field=models.IntegerField(null=True),
        ),
    ]
