# Generated by Django 2.2.7 on 2024-05-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0062_auto_20240417_1310"),
        ("jobs", "0051_tmeta_message_templates_jd_id"),
    ]

    operations = []
