# Generated by Django 2.2.7 on 2024-05-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0060_auto_20240421_0349"),
        ("jobs", "0063_merge_20240506_0519"),
    ]

    operations = []
