# Generated by Django 2.2.7 on 2024-05-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0064_merge_20240506_0532"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tmeta_coresignal_data",
        ),
    ]
