# Generated by Django 2.2.7 on 2024-05-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0065_delete_tmeta_coresignal_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline_status",
            name="status_on",
            field=models.TextField(null=True),
        ),
    ]
