# Generated by Django 2.2.7 on 2024-05-10 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0066_pipeline_status_status_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tmeta_message_templates",
            name="jd_id",
        ),
        migrations.CreateModel(
            name="jd_message_templates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("subject", models.TextField(null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("stage", models.IntegerField(null=True)),
                ("status", models.BooleanField(null=True)),
                (
                    "jd_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.JD_form",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.tmeta_message_templates",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
