# Generated by Django 2.2.7 on 2024-05-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0067_auto_20240510_0328"),
    ]

    operations = [
        migrations.AddField(
            model_name="tmeta_message_templates",
            name="jd_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.JD_form",
            ),
        ),
    ]
