# Generated by Django 2.2.7 on 2024-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0068_tmeta_message_templates_jd_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="jd_message_templates",
            name="templates",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="jd_message_templates",
            name="templates_text",
            field=models.TextField(null=True),
        ),
    ]
