# Generated by Django 2.2.7 on 2024-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0069_auto_20240513_1142"),
    ]

    operations = [
        migrations.CreateModel(
            name="tmeta_email_tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("tag", models.TextField(null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
