# Generated by Django 2.2.7 on 2024-08-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0070_tmeta_email_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching_loader',
            name='candidate_id',
        ),
    ]
