# Generated by Django 2.2.7 on 2024-08-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0072_job_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_board',
            old_name='jd_id',
            new_name='job_id',
        ),
    ]
