# Generated by Django 2.2.7 on 2024-09-11 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0073_auto_20240829_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_addons_purchase_history',
            name='plan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.tmeta_plan'),
        ),
    ]
