# Generated by Django 2.2.7 on 2024-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0077_zita_api_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='zita_api_service',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
