# Generated by Django 2.2.7 on 2024-10-08 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0078_zita_api_service_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_codes_claimed',
            name='subscription_id',
        ),
        migrations.AlterField(
            model_name='discount_codes_claimed',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
