# Generated by Django 2.2.7 on 2024-10-08 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0079_auto_20241008_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_codes_claimed',
            name='subscription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.subscriptions'),
        ),
        migrations.AlterField(
            model_name='discount_codes_claimed',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='discount_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_date', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discount_addon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.discounts_addon')),
                ('discount_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.discounts')),
            ],
        ),
    ]
