# Generated by Django 2.2.7 on 2024-10-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0080_auto_20241008_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_user',
            name='discount_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount_user',
            name='discount_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
