# Generated by Django 2.2.7 on 2024-10-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0082_auto_20241011_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='discounts_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.tmeta_addons')),
                ('discount_addon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.discounts_addon')),
                ('discount_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.discounts')),
                ('plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.tmeta_plan')),
            ],
        ),
    ]
