# Generated by Django 2.2.7 on 2024-10-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0083_discounts_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd_form',
            name='job_id',
            field=models.CharField(max_length=50),
        ),
    ]
