# Generated by Django 2.2.7 on 2024-10-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0083_discounts_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_board',
            new_name='job_board_list',
        ),
    ]
