# Generated by Django 2.2.7 on 2024-10-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0084_auto_20241017_0745'),
        ('jobs', '0084_auto_20241016_0603'),
    ]

    operations = [
    ]
