# Generated by Django 2.2.7 on 2023-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="website_details",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addons", models.TextField(null=True)),
                ("card_view", models.TextField(null=True)),
            ],
        ),
    ]
