# name: Code Review with CodeRabbit AI

# on:
#   pull_request:
#     branches:
#       - '**'

# jobs:
#   review:
#     name: Analyze Code Changes with CodeRabbit AI
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       # Assuming CodeRabbit is available as a GitHub Action or external service
#       - name: Run CodeRabbit AI Code Review
#         run: |
#           # Example command to run CodeRabbit AI code analysis (replace with actual integration)
#           curl -X POST https://api.coderabbit.ai/review --header "Authorization: Bearer ${{ secrets.CODERABBIT_API_KEY }}" --data-urlencode "repo_url=${{ github.repository }}" --data-urlencode "pr_url=${{ github.event.pull_request.html_url }}" 

#       - name: Comment on PR with Results
#         run: |
#           curl -X POST --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
#           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#           -d '{"body": "CodeRabbit AI Code Review Suggestions: \n\n'$(cat result.txt)'}' 
name: Code Review with CodeRabbit AI

on:
  pull_request:
    branches:
      - '**'

jobs:
  review:
    name: Analyze Code Changes with CodeRabbit AI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CodeRabbit AI Code Review
        run: |
          curl -X POST https://api.coderabbit.ai/review --header "Authorization: Bearer ${{ secrets.CODERABBIT_API_KEY }}" \
            --data-urlencode "repo_url=${{ github.repository }}" \
            --data-urlencode "pr_url=${{ github.event.pull_request.html_url }}" \
            -o result.txt 

      - name: Comment on PR with Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Replace with PERSONAL_ACCESS_TOKEN if needed
        run: |
          if [ -s result.txt ]; then
            curl -X POST --url "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"body": "CodeRabbit AI Code Review Suggestions:\n\n'$(cat result.txt)'}'
          else
            echo "No output from CodeRabbit AI"
          fi
